// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'models/todo', 'backboneLocalStorage'], function(Backbone, TodoModel, Store) {
    var Todos, _ref;
    Todos = (function(_super) {
      __extends(Todos, _super);

      function Todos() {
        _ref = Todos.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Todos.prototype.model = TodoModel;

      Todos.prototype.localStorage = new Store('todos-storage');

      Todos.prototype.completed = function() {
        return this.filter(function(todo) {
          return todo.get('completed');
        });
      };

      Todos.prototype.remaining = function() {
        return this.without.apply(this, this.completed);
      };

      Todos.prototype.nextOrder = function() {
        if (!this.length) {
          return 1;
        } else {
          return this.last().get('order') + 1;
        }
      };

      Todos.prototype.comparator = function(todo) {
        return todo.get('order');
      };

      return Todos;

    })(Backbone.Collection);
    return Todos;
  });

}).call(this);
