// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function(Backbone) {
    var Todo, _ref;
    Todo = (function(_super) {
      __extends(Todo, _super);

      function Todo() {
        _ref = Todo.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Todo.prototype.defaults = {
        title: '',
        completed: false
      };

      Todo.prototype.toggle = function() {
        return this.save({
          completed: !this.get('completed')
        });
      };

      return Todo;

    })(Backbone.Model);
    return Todo;
  });

}).call(this);

/*
//@ sourceMappingURL=todo.map
*/
